# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='public',
            field=models.NullBooleanField(choices=[('F', False), ('T', True)], default=False),
        ),
    ]
